version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./ETL_idea4rc_to_omop:/home/jovyan/work
    ports:
      - 8884:8888
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token="
    user: "${UID}:${GID}"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: omop_mariadb
    environment:
      MYSQL_DATABASE: omopdb
      MYSQL_USER: user
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_ROOT_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5